#!/usr/bin/env bash
# =============================================================================
# devstack_install.sh — Automated OpenStack DevStack Installer
# =============================================================================
# Installs a single-node OpenStack DevStack environment on Ubuntu 22.04.
# Run this script on the HOST machine (not inside a VM).
#
# Usage:
#   sudo bash devstack_install.sh
#
# What this script does:
#   1. Installs prerequisites (git, python3, curl)
#   2. Creates the 'stack' user required by DevStack
#   3. Clones DevStack from OpenDev
#   4. Auto-detects host IP and writes local.conf
#   5. Runs stack.sh as the 'stack' user
#   6. Verifies the installation
# =============================================================================

set -e

BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
CYAN="\033[0;36m"
RESET="\033[0m"

info()    { echo -e "${GREEN}[INFO]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET} $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }
section() { echo -e "\n${BOLD}${CYAN}==> $*${RESET}"; }

# ─── Must run as root ─────────────────────────────────────────────────────────
if [[ "$EUID" -ne 0 ]]; then
    error "Please run as root: sudo bash devstack_install.sh"
fi

# ─── Configuration (edit these if needed) ─────────────────────────────────────
DEVSTACK_BRANCH="stable/2024.2"          # DevStack branch to use
STACK_USER="stack"                        # DevStack must run as this user
STACK_HOME="/opt/stack"                   # Home directory for stack user
DEVSTACK_DIR="${STACK_HOME}/devstack"     # Where DevStack will be cloned

# Passwords — change these for production
ADMIN_PASSWORD="secret"
DATABASE_PASSWORD="secret"
RABBIT_PASSWORD="secret"
SERVICE_PASSWORD="secret"

# ─── 1. Check OS ──────────────────────────────────────────────────────────────
section "Checking OS"
if ! grep -qi "ubuntu" /etc/os-release 2>/dev/null; then
    warn "This script is tested on Ubuntu 22.04. Proceeding anyway..."
fi
OS_VERSION=$(grep VERSION_ID /etc/os-release | cut -d= -f2 | tr -d '"')
info "OS version: ${OS_VERSION}"

# ─── 2. Install prerequisites ─────────────────────────────────────────────────
section "Installing prerequisites"
apt-get update -qq
apt-get install -y git python3 python3-pip curl wget net-tools sudo
info "Prerequisites installed."

# ─── 3. Detect host IP ────────────────────────────────────────────────────────
section "Detecting host IP"
HOST_IP=$(ip route get 8.8.8.8 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)
if [[ -z "$HOST_IP" ]]; then
    HOST_IP=$(hostname -I | awk '{print $1}')
fi
if [[ -z "$HOST_IP" ]]; then
    error "Could not detect host IP. Set HOST_IP manually in this script."
fi
info "Host IP detected: ${HOST_IP}"

# ─── 4. Create 'stack' user ───────────────────────────────────────────────────
section "Creating '${STACK_USER}' user"
if id "${STACK_USER}" &>/dev/null; then
    info "User '${STACK_USER}' already exists."
else
    useradd -s /bin/bash -d "${STACK_HOME}" -m "${STACK_USER}"
    info "User '${STACK_USER}' created with home: ${STACK_HOME}"
fi

# Grant passwordless sudo to stack user
if ! grep -q "^${STACK_USER}" /etc/sudoers 2>/dev/null; then
    echo "${STACK_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    info "Passwordless sudo granted to '${STACK_USER}'."
fi

# ─── 4b. Cleanup previous DevStack installation (automatic, no prompt) ────────
section "Checking for existing DevStack installation"
if [[ -d "${DEVSTACK_DIR}" ]]; then
    warn "Existing DevStack found at ${DEVSTACK_DIR}. Cleaning up automatically..."
    # Gracefully stop all DevStack services first (if unstack.sh exists)
    if [[ -f "${DEVSTACK_DIR}/unstack.sh" ]]; then
        info "Running unstack.sh to stop DevStack services..."
        sudo -u "${STACK_USER}" bash "${DEVSTACK_DIR}/unstack.sh" 2>/dev/null || true
        info "unstack.sh completed."
    fi
    # Remove ONLY the devstack clone directory.
    # Does NOT touch /opt/stack/data, logs, or any other critical directories.
    rm -rf "${DEVSTACK_DIR}"
    info "DevStack directory removed. Starting fresh install."
fi

# ─── 5. Clone DevStack ────────────────────────────────────────────────────────
section "Cloning DevStack (branch: ${DEVSTACK_BRANCH})"
sudo -u "${STACK_USER}" git clone \
    https://opendev.org/openstack/devstack \
    --branch "${DEVSTACK_BRANCH}" \
    "${DEVSTACK_DIR}"
info "DevStack cloned to ${DEVSTACK_DIR}"

# ─── 6. Write local.conf ──────────────────────────────────────────────────────
section "Writing DevStack local.conf"
cat > "${DEVSTACK_DIR}/local.conf" <<EOF
[[local|localrc]]
# =============================================================================
# DevStack local.conf — 4K Video Transcoder Deployment
# Generated by devstack_install.sh
# =============================================================================

# Passwords
ADMIN_PASSWORD=${ADMIN_PASSWORD}
DATABASE_PASSWORD=${DATABASE_PASSWORD}
RABBIT_PASSWORD=${RABBIT_PASSWORD}
SERVICE_PASSWORD=${SERVICE_PASSWORD}

# Host IP
HOST_IP=${HOST_IP}

# Branch — uses DEVSTACK_BRANCH variable set at top of this script
OPENSTACK_BRANCHES=${DEVSTACK_BRANCH}

# ── Core Services ─────────────────────────────────────────────────────────────
# Compute
enable_service n-api
enable_service n-cpu
enable_service n-cond
enable_service n-sch
enable_service n-novnc
enable_service n-api-meta
enable_service placement-api
enable_service placement-client

# Networking (Neutron + OVN)
# IMPORTANT: stable/2024.2 uses OVN as the default ML2 mechanism driver.
# The legacy agents q-agt, q-dhcp, q-l3, q-meta are ML2/OVS agents and
# are INCOMPATIBLE with OVN — enabling them causes:
#   [ERROR] The q-agt/neutron-agt service must be disabled with OVN.
enable_service neutron
enable_service q-svc
enable_service q-ovn-metadata-agent

# OVN ML2 driver — explicit config to avoid ambiguity
Q_AGENT=ovn
Q_ML2_PLUGIN_MECHANISM_DRIVERS=ovn
Q_ML2_PLUGIN_TYPE_DRIVERS=local,flat,vlan,geneve

# Image service (g-reg is deprecated/removed in OpenStack 2024.x — merged into g-api)
enable_service g-api

# Identity
enable_service keystone

# Block storage (for persistent video storage)
enable_service cinder
enable_service c-api
enable_service c-vol
enable_service c-sch

# Dashboard (Horizon) — comment out to speed up install
enable_service horizon

# ── Disable services not needed ───────────────────────────────────────────────
disable_service tempest
disable_service swift

# ── Logging ───────────────────────────────────────────────────────────────────
LOGFILE=\$DEST/logs/stack.sh.log
VERBOSE=True
LOG_COLOR=True
LOGDAYS=1

# ── Image ─────────────────────────────────────────────────────────────────────
# Use Ubuntu 22.04 cloud image for VMs
IMAGE_URLS="https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
EOF

chown "${STACK_USER}:${STACK_USER}" "${DEVSTACK_DIR}/local.conf"
info "local.conf written to ${DEVSTACK_DIR}/local.conf"

# ─── 6b. Pre-configure MySQL for Ubuntu 24.04 (Noble) ────────────────────────
section "Pre-configuring MySQL for Ubuntu 24.04 compatibility"
# Ubuntu 24.04 Noble uses auth_socket plugin for MySQL root by default.
# DevStack's configure_database_mysql does:
#   1. sudo mysqladmin -u root password secret   (works via socket)
#   2. sudo mysql -uroot -psecret -h127.0.0.1    (FAILS — still auth_socket)
# Fix: pre-install MySQL and switch root to mysql_native_password BEFORE stack.sh.
info "Installing MySQL server (pre-install for auth fix)..."
DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server 2>/dev/null || true
info "Starting MySQL service..."
systemctl start mysql 2>/dev/null || true
sleep 3
info "Disabling MySQL validate_password component (MySQL 8.0 rejects 'secret')..."
# MySQL 8.0 on Ubuntu 24.04 installs validate_password component by default.
# It rejects simple passwords like 'secret'. Uninstall it first.
mysql -u root -e "UNINSTALL COMPONENT 'file://component_validate_password';" 2>/dev/null || \
    mysql -u root -e "SET GLOBAL validate_password.policy=LOW; SET GLOBAL validate_password.length=1;" 2>/dev/null || true

info "Switching MySQL root to mysql_native_password (password: secret)..."
if mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'secret'; FLUSH PRIVILEGES;" 2>/dev/null; then
    info "MySQL root auth pre-configured: mysql_native_password / secret ✓"
else
    warn "MySQL pre-config may have failed — DevStack will attempt its own setup."
fi

# ─── 7. Run stack.sh ──────────────────────────────────────────────────────────
section "Running stack.sh (this takes 20–40 minutes)"
info "Logs: ${STACK_HOME}/logs/stack.sh.log"
echo ""
warn "Do NOT interrupt this process. It will take 20–40 minutes."
echo ""

cd "${DEVSTACK_DIR}"
sudo -u "${STACK_USER}" bash "${DEVSTACK_DIR}/stack.sh"

# ─── 8. Post-install verification ─────────────────────────────────────────────
section "Verifying DevStack installation"

OPENRC="${DEVSTACK_DIR}/openrc"
if [[ ! -f "${OPENRC}" ]]; then
    error "openrc file not found at ${OPENRC}. DevStack may have failed."
fi

# Source credentials and run a quick check
sudo -u "${STACK_USER}" bash -c "
    source ${OPENRC} admin admin
    echo '[CHECK] OpenStack services:'
    openstack service list
    echo ''
    echo '[CHECK] Available images:'
    openstack image list
    echo ''
    echo '[CHECK] Available flavors:'
    openstack flavor list
"

# ─── 9. Summary ───────────────────────────────────────────────────────────────
section "DevStack Installation Complete"
echo ""
echo -e "${BOLD}DevStack is running!${RESET}"
echo ""
echo "  Horizon Dashboard : http://${HOST_IP}/dashboard"
echo "  Admin credentials : admin / ${ADMIN_PASSWORD}"
echo "  OpenRC file       : ${DEVSTACK_DIR}/openrc"
echo ""
echo -e "${BOLD}Next step — deploy the transcoder app:${RESET}"
echo ""
echo "  1. Source OpenStack credentials:"
echo "       source ${DEVSTACK_DIR}/openrc admin admin"
echo ""
echo "  2. Run the deployment script:"
echo "       bash openstack_deploy.sh"
echo ""
echo -e "${GREEN}DevStack setup finished successfully.${RESET}"
